apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.office365.com:587'
      smtp_from:
        valueFrom:
          secretKeyRef:
            name: alert-credentials
            key: smtp_auth_username
      smtp_auth_username:
        valueFrom:
          secretKeyRef:
            name: alert-credentials
            key: smtp_auth_username
      smtp_auth_password:
        valueFrom:
          secretKeyRef:
            name: alert-credentials
            key: smtp_auth_password
      smtp_require_tls: true

    route:
      receiver: 'email-alerts'
      group_by:
        - 'alertname'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h

    receivers:
      - name: 'email-alerts'
        email_configs:
          - to: 'njjmma.1@outlook.com'
            send_resolved: true
