apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: expensy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: najjaved/expensy-backend:__IMAGE_TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 8706
          env:           
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: expensy-secrets
                  key: DATABASE_URI

            - name: REDIS_PORT
              value: "6379"

            - name: REDIS_HOST
              value: "redis-service" # Reference the corresponding service name

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: expensy-secrets
                  key: redis-password

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: expensy
  labels:
    app: backend # for prometheus
spec:
  selector:
    app: backend
  ports:
    - name: http # port label
      port: 8706 # external port exposed by the service
      targetPort: 8706 # actual port inside the pod 
  type: ClusterIP
