apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: expensy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: sjagtap0/frontend
          ports:
            - containerPort: 3002
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://backend-service:8706"  # The backend service URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
