apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expensy-ingress
  namespace: expensy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  # Cert-Manager creates a Certificate resource in the background automatically
  tls:
  - hosts:
    - najhack.online
    secretName: expensy-tls  # cert will be stored here 
  rules:
    - host: najhack.online
      http:
        paths:
          # - path: /expensy
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: frontend-service
          #       port:
          #         number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
    - host: api.najhack.online
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service  # Backend service for path /api
                port:
                  number: 8706  # Port exposed by the backend service