apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-app-ingress
spec:
  ingressClassName:  "nginx"
  rules:
    - http:
        paths:
          - path: /expensy
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3002
          - path: /
            pathType: Exact
            backend:
                service:
                  name: frontend-service
                  port:
                    number: 3002
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3002