apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expensy-ingress
  namespace: expensy
spec:
  ingressClassName: nginx
  rules:
    - host: 20.203.52.255.nip.io
      http:
        paths:
          - path: /expensy
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
          - path: /
            pathType: Exact
            backend:
                service:
                  name: frontend-service
                  port:
                    number: 3000
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000