    # Run this workflow after the 'CI Pipeline' workflow has completed on the dev branch
    name: CD Pipeline
    run-name: ${{ github.actor }} is Deploying
    
    
    on:
      workflow_run:
        workflows:
          - CI Pipeline
        types:
          - completed
        branches:
          - dev
       
    jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0  # Ensures all files are downloaded

            - name: Install Azure CLI
              run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash # or  uses: azure/CLI@v1 
            - name: Verify Installation
              run: |
                az --version
    
            - name: Install kubectl
              run: |
                sudo az aks install-cli
                kubectl version --client
              
            - name: Login to Azure
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
              
            - name: Connect to AKS Cluster
              run:  az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

            - name: Verify cluster access
              run: kubectl get nodes

            - name: Set IMAGE_TAG from Git ref
              run: echo "IMAGE_TAG=${{ github.ref_type == 'tag' && github.ref_name || github.sha }}" >> $GITHUB_ENV
            
            - name: Replace IMAGE_TAG in manifests
              run: |
                sed "s/__IMAGE_TAG__/${IMAGE_TAG}/g" k8s/frontend.tpl.yml > k8s/frontend.yml
                sed "s/__IMAGE_TAG__/${IMAGE_TAG}/g" k8s/backend.yml.yml > k8s/backend.yml
            
    
            - name: Deploy workloads to AKS in expensy namespace
              run: |
                kubectl apply -f k8s/ -n expensy
