name: CI Pipeline
run-name: ${{ github.actor }} is Deploying

on:
  push:
    branches: 
      - swap-feature-branch
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
      REGISTRY: docker.io
      IMAGE_FRONTEND: ${{ secrets.DOCKERHUB_USERNAME }}/expensy_frontend
      IMAGE_BACKEND: ${{ secrets.DOCKERHUB_USERNAME }}/expensy_backend

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker images
        run: |
          docker-compose build

          echo "Tagging and pushing images..."
          docker tag expensy_frontend:latest $IMAGE_FRONTEND:$IMAGE_TAG
          docker tag expensy_backend:latest $IMAGE_FRONTEND:latest

          docker push $IMAGE_FRONTEND:$IMAGE_TAG
          docker push $IMAGE_FRONTEND:latest

          docker tag expensy_backend:latest $IMAGE_BACKEND:$IMAGE_TAG
          docker tag expensy_backend:latest $IMAGE_BACKEND:latest


          docker push $IMAGE_BACKEND:$IMAGE_TAG
          docker push $IMAGE_BACKEND:latest

