name: CI Pipeline

on:
  push:
    branches: 
      - '*'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:new ./expensy_frontend --build-arg NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:new ./expensy_backend

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:new
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:new
